title: Leonardo's Portfolio
description: Hi, I'm Leonardo, but you can call me Leo, a guy passionate about creating pleasurable & functional websites.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
